#!/bin/bash

# Remind users to set up passwordless ssh, clush and visudo

echo "Before running this script, you need to set up passwordless ssh and copy cloud-init.sh"

# Install ancillary packages 
clush --hostfile /home/minio/minio-nodes sudo apt install sysstat iperf clustershell git prometheus prometheus-process-exporter prometheus-node-exporter



# Download AIStor components
wget https://dl.min.io/aistor/mc/release/linux-amd64/mc
wget https://dl.min.io/aistor/minio/release/linux-amd64/minio
wget https://dl.min.io/aistor/minkms/release/linux-amd64/minkms
wget https://dl.min.io/aistor/minwall/release/linux-amd64/minwall
wget https://dl.min.io/aistor/mincat/release/linux-amd64/mincat

# Download benchmarking tools 
wget https://github.com/minio/hperf/releases/latest/download/hperf-linux-amd64 -O hperf
wget https://github.com/minio/dperf/releases/latest/download/dperf-linux-amd64 -O dperf

# Since warp has no direct link, use this monstrosity  -- it almost certainly will break in the future
wget https://github.com/minio/warp/releases/download/$(curl https://github.com/minio/warp/releases/ | grep tree | grep -v script | head -n1 |cut -b 33-38)/warp_Linux_x86_64.tar.gz

# Unpack warp
tar -xvzf warp_Linux_x86_64.tar.gz

# Make binaries executable
chmod +x mc minio minkms minwall mincat hperf dperf warp

# Copy assets to remote nodes
clush --hostfile /home/minio/minio-nodes --copy * --dest /tmp

# Make generic asset / config dir for minio
clush --hostfile /home/minio/minio-nodes sudo mkdir /etc/minio

# Copy systemd service files
clush --hostfile /home/minio/minio-nodes sudo cp /tmp/*service /etc/systemd/system/

# Copy binaries to $PATH
clush --hostfile /home/minio/minio-nodes sudo cp /tmp/mc /tmp/minio /tmp/minkms /tmp/minwall /tmp/mincat /usr/local/bin

# Copy config files to generic location
clush --hostfile /home/minio/minio-nodes  sudo cp /tmp/*config /tmp/public.crt /tmp/private.key /etc/minio/


# Grafana setup 
# TODO

# Prometheus setup
# TODO
                                                                                                                                                           5,93          Top

